# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# dummy comment

version: 2
updates:  
  - package-ecosystem: "devcontainers" # See documentation for possible values
    directory: "/.devcontainer/functions/"
    schedule:
      interval: "daily"
    groups:
       devcontainers-dependencies:
          patterns:
            - "*"

  - package-ecosystem: "devcontainers" # See documentation for possible values
    directory: "/.devcontainer/node.js/"
    schedule:
      interval: "daily"
    groups:
       devcontainers-dependencies:
          patterns:
            - "*"
